import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavDesktop from "@/components/headers/NavDesktop";

const geistSans = Geist({ subsets: ["latin"], variable: "--font-geist-sans" });
const geistMono = Geist_Mono({ subsets: ["latin"], variable: "--font-geist-mono" });

export const metadata = {
  title: "Create first app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <NavDesktop />
        <main>{children}</main>
      </body>
    </html>
  );
}
